name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Trigger deployment only on main branch push

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Make sure you're pointing to the dist directory
          publish_branch: gh-pages  # Deploy to gh-pages branch (not main)
          force_orphan: true  # Ensures clean commit history
